# Generated by Django 2.0.13 on 2019-04-14 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.TextField(blank=True, default='')),
                ('posts', models.PositiveSmallIntegerField(default=0, null=True)),
                ('subscriptions', models.CharField(blank=True, default='', max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ('time_created',),
            },
        ),
    ]
