# Generated by Django 2.0.13 on 2019-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readposts',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
